PRESETS = {
    'morning_coffee': {
        'name': '아침 커피 타임',
        'description': '따뜻하고 편안한 아침 분위기',
        'tempo': 72,
        'chord_progression': [
            ('C', 'maj7'), ('F', 'maj7'), ('A', 'min7'), ('G', 'sus4'),
        ],
        'instruments': {'piano': 0, 'bass': 32, 'pad': 48},
        'piano_style': 'arpeggiate',
        'bass_style': 'simple',
        'percussion': 'minimal',
        'piano_velocity': 72,
        'bass_velocity': 60,
        'pad_velocity': 50,
        'background': 'morning',
        'youtube_tags': ['아침음악', '커피타임', '힐링음악', '잔잔한음악', 'morningmusic', 'ambient'],
    },
    'meditation': {
        'name': '명상 음악',
        'description': '깊은 명상과 마음의 평온을 위한 음악',
        'tempo': 58,
        'chord_progression': [
            ('D', 'min7'), ('F', 'maj7'), ('G', 'min7'), ('A', 'min7'),
        ],
        'instruments': {'piano': 0, 'bass': 35, 'pad': 52},
        'piano_style': 'sparse',
        'bass_style': 'sustained',
        'percussion': 'none',
        'piano_velocity': 58,
        'bass_velocity': 50,
        'pad_velocity': 60,
        'background': 'nature',
        'youtube_tags': ['명상음악', '힐링', '마음챙김', 'meditation', 'relaxing', 'ambient'],
    },
    'sleep': {
        'name': '수면 음악',
        'description': '편안하게 잠들 수 있는 부드러운 음악',
        'tempo': 52,
        'chord_progression': [
            ('A', 'maj7'), ('D', 'maj7'), ('F#', 'min7'), ('E', 'sus4'),
        ],
        'instruments': {'piano': 0, 'bass': 35, 'pad': 48},
        'piano_style': 'sparse',
        'bass_style': 'sustained',
        'percussion': 'none',
        'piano_velocity': 52,
        'bass_velocity': 45,
        'pad_velocity': 48,
        'background': 'night',
        'youtube_tags': ['수면음악', '잠잘때음악', '수면유도', 'sleepmusic', 'relaxing', 'ambient'],
    },
    'study_focus': {
        'name': '공부 집중 음악',
        'description': '집중력을 높여주는 잔잔한 로파이 음악',
        'tempo': 80,
        'chord_progression': [
            ('G', 'maj7'), ('C', 'maj7'), ('A', 'min7'), ('D', 'dom7'),
        ],
        'instruments': {'piano': 4, 'bass': 33, 'pad': 48},
        'piano_style': 'arpeggiate',
        'bass_style': 'walking',
        'percussion': 'lofi',
        'piano_velocity': 75,
        'bass_velocity': 68,
        'pad_velocity': 45,
        'background': 'study',
        'youtube_tags': ['공부음악', '집중음악', '로파이', 'lofi', 'studymusic', 'focus'],
    },
    'rainy_day': {
        'name': '비오는 날 음악',
        'description': '빗소리와 함께 듣기 좋은 감성 음악',
        'tempo': 66,
        'chord_progression': [
            ('E', 'min7'), ('A', 'min7'), ('D', 'maj7'), ('G', 'maj7'),
        ],
        'instruments': {'piano': 0, 'bass': 32, 'pad': 48},
        'piano_style': 'block_chord',
        'bass_style': 'simple',
        'percussion': 'minimal',
        'piano_velocity': 65,
        'bass_velocity': 58,
        'pad_velocity': 52,
        'background': 'rain',
        'youtube_tags': ['비오는날음악', '감성음악', '힐링', 'rainyday', 'chillmusic', 'ambient'],
    },
}
